// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package berci_bank

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Owner     pgtype.Text
	Balance   pgtype.Int8
	Currency  pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Entry struct {
	ID        int64
	AccountID pgtype.Int8
	Amount    pgtype.Int8
	CreatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// must be positive
	Amount    int64
	CreatedAt pgtype.Timestamptz
}
